### ISSUE TITLE
No module named 'AtlasI2C'

### ISSUE THREAD

**Issue by mauriceatkinson** [sighmon/water-quality-lorawan-dragino-pi#1]
I have the installed the two github libaries and can make a join request to the TTN.

However when I run python3 water_quality.py the following error is received:

pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python3 water_quality.py
Traceback (most recent call last):
  File "water_quality.py", line 17, in <module>
    from AtlasI2C import (
ModuleNotFoundError: No module named 'AtlasI2C'

However it appears that the atlas-i2c module is installed:
pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ sudo pip3 install atlas-i2c
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: atlas-i2c in /usr/local/lib/python3.7/dist-packages (0.3.1)

If I run the command python water_quality.py
The following error is displayed:

pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python water_quality.py
  File "water_quality.py", line 85
    print(".", end="")
                  ^
SyntaxError: invalid syntax

**Comment by sighmon** [comment]
@mauriceatkinson Ah great thanks - try a `git pull` and see if the import works now.

Also, you'll need to run it with `python3` and not `python` just incase you have Python 2 installed.

**Comment by mauriceatkinson** [comment]
@sighmon thanks, I have run it again and got:

Traceback (most recent call last):
  File "water_quality.py", line 18, in <module>
    from dragino import Dragino
ModuleNotFoundError: No module named 'dragino'

**Comment by sighmon** [comment]
@mauriceatkinson How did you install `dragino`?

**Comment by mauriceatkinson** [comment]
@sighmon I followed the instructions from here https://github.com/BNNorman/dragino-1

**Comment by mauriceatkinson** [comment]
@sighmon 
Hi Simon
I started from scratch again and below is how I installed. 

 On running your program I got the error:
pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python3 water_quality.py

Connected EZO devices:
Traceback (most recent call last):
  File "water_quality.py", line 101, in <module>
    main()
  File "water_quality.py", line 73, in main
    ezo_device_list = get_ezo_devices()
  File "water_quality.py", line 35, in get_ezo_devices
    device_address_list = device.list_i2c_devices()
AttributeError: 'AtlasI2C' object has no attribute 'list_i2c_devices'




==================================================

Rasp Pi
Installed Buster 2022-01-28
Sudo apt-get update
Sudo apt-get upgrade
Raspi-config enable ssh,vnc,i2c,serial port hardware

Whitebox
git clone https://github.com/whitebox-labs/whitebox-raspberry-ezo.git
(tested I could receive i2c sensor values)


Dragino
sudo apt install device-tree-compiler git python3-crypto python3-nmea2 python3-rpi.gpio python3-serial python3-spidev python3-configobj
git clone https://github.com/BNNorman/dragino-1.git
cd dragino-1/overlay
dtc -@ -I dts -O dtb -o spi-gpio-cs.dtbo spi-gpio-cs-overlay.dts
sudo cp spi-gpio-cs.dtbo /boot/overlays/
sudo pip3 install toml
sudo apt-get install gpsd gpsd-clients python-gps
sudo pip3 install gps3
(tested I could join and send hello message to TTN)
sudo pip3 install atlas-i2c

Water Quality
Git clone https://github.com/sighmon/water-quality-lorawan-dragino-pi.git
Copy dragino folder from repo https://github.com/BNNorman/dragino-1.git into water quality directory

**Comment by sighmon** [comment]
@mauriceatkinson Looks like the pip installed `atlas-i2c` library doesn't have the command we need to list all of the sensors. So try:

1. `git pull` from the water quality directory to revert the import change I made
1. `sudo pip3 uninstall atlas-i2c`
1. Copy [AtlasI2C.py](https://github.com/whitebox-labs/whitebox-raspberry-ezo/blob/master/AtlasI2C.py) into the water quality directory
1. Run `python3 water_quality.py`

**Comment by mauriceatkinson** [comment]
@sighmon
That looks much better I now see the sensor data being retrieved.  However the sensor data is not being transferred to the TTN network.  When I run the test.py in the whitebox repo I see data being transferred to TTN but not when I run the water_quality.py


pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python3 water_quality.py

Connected EZO devices:

pH 99
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP

**Comment by sighmon** [comment]
@mauriceatkinson I've added a couple more print statements to see if it is even trying to connect to the TTN network. So do another `git pull` and see where it's failing.

There's a chance that the Dragino library is using the same gpio as the Atlas library causing problems, but hopefully not.

**Comment by mauriceatkinson** [comment]
@sighmon this is the output I get when running the water_quality.py

Connected EZO devices:

pH 99

Starting dragino connection to TTN
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP

**Comment by sighmon** [comment]
@mauriceatkinson Do you want to check which pins the `dragino` and `Atlas` sensors use? Maybe post in a dragino forum to see what those modes mean?

**Comment by mauriceatkinson** [comment]
@sighmon 
This is what I had which indicates no conflict but I will ask around.
https://github.com/dragino/Lora/blob/master/Lora_GPS%20HAT/v1.4/Lora%20GPS%20%20HAT%20for%20RPi%20v1.4.pdf
https://www.whiteboxes.ch/docs/tentacle/t3-mkII/#/pinout?id=-pinout

**Comment by mauriceatkinson** [comment]
@sighmon my mistake as the dragino.toml file was not in the correct folder.  that will teach me not to look at the error log first!!

The value is now transmitted and received by TTN then forwarded on via mqtt to my Home Assistant.  Which is great step forward.

I think the sensor value is encoded but I will double check this.

I also need to work out how often I can send messages through the TTN so I may be asking for some changes in relation to the trasnmission delay.

**Comment by mauriceatkinson** [comment]
@sighmon 
Currently I have only one sensor connected so not clear what the input format will be.  I am waiting for the rest of the sensors  to be with me...maybe Monday.  However wanted to show you what is being received by TTN in base64 format .  

Maybe after I have connected the rest of the sensors we can work out what is the best format to send the data.  I want to keep the transfer as small as possible so things like "sucess" is overkill and not needed to be sent.


transmitted encoded data
U3VjY2VzcyBwSCA5OSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6IDAuMDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

decoded data
Success pH 99 ������������������������: 0.000�������������������������

**Comment by sighmon** [comment]
@mauriceatkinson Fantastic news! That's great it's transmitting the data well.

Yes, the formatting will take some work, and we'll want to transmit the minimum as you say. But nothing a decent [regex](https://regexr.com) can't fix.

If you'd like to add me to your TTN application I can help with the decoding if need be, my User ID is `sighmon` there too.

**Comment by mauriceatkinson** [comment]
Great to hear you know what to do!!  I have added you to the TTN app.  Nothing is written in stone and can be changed so feel free to do what you think is best.

**Comment by sighmon** [comment]
@mauriceatkinson I can see the application `aarc-sensors` but can't see any data packets from any devices.

Can you post what's on the console before it sends it to the TTN please?

e.g. What gets printed after: `Sending data from devices: `

**Comment by mauriceatkinson** [comment]
@sighmon Sorry I switched off the sensor but it is back on again now.

this is what the rasp pi is showing on when running your py code:
pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python3 water_quality.py

Connected EZO devices:

pH 99

Starting dragino connection to TTN
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP

Waiting for JOIN ACCEPT

Joined
Sending data from devices: Success pH 99 : 14.000
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT
Sending data from devices: Success pH 99 : 0.000
Mode <- SLEEP
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT
Sending data from devices: Success pH 99 : 0.000
Mode <- SLEEP
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT
Sending data from devices: Success pH 99 : 0.000
Mode <- SLEEP
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT
Sending data from devices: Success pH 99 : 0.000
Mode <- SLEEP
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT
Sending data from devices: Success pH 99 : 0.000
Mode <- SLEEP
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT

**Comment by mauriceatkinson** [comment]
@sighmon I have 5 (although only 3 are reporting a value - I have to check why this is the case) of the 7 sensors installed, the others are hopefully coming next week.

All looks great when running your program and this is what prints out this on the pi:
pi@raspberrypi:~/water-quality-lorawan-dragino-pi $ python3 water_quality.py

Connected EZO devices:

DO 97

pH 99

RTD 102

Starting dragino connection to TTN
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP
Mode <- FSK_STDBY
Mode <- SLEEP

Waiting for JOIN ACCEPT

Joined
Sending data from devices: Success DO 97 : 38.29|Success pH 99 : 13.679|Success RTD 102 : -1023.000
Mode <- RXCONT
Mode <- STDBY
Mode <- TX
Mode <- STDBY
Mode <- SLEEP
Mode <- RXCONT

This is the TTN payload:
U3VjY2VzcyBETyA5NyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6IDM4LjI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHxTdWNjZXNzIHBIIDk5IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADogMTAuNDY4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfFN1Y2Nlc3MgUlREIDEwMiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6IC0xMDIzLjAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==


This what is decoded string from TTN
"Success DO 97 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000: 38.28\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000|Success pH 99 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000: 10.468\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000|Success RTD 102 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000: -1023.000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"

I have not left it running as the Pi exceeds the TTN duty cycle.  Your programs states 1% duty cycle but in reading this is the EU/UK ETSI duty cycle.  The TTN duty cycle is actually 0.3% as a device can only send 30 seconds worth of data within a 24 hour period.  Is this something you could change in your program?

**Comment by sighmon** [comment]
@mauriceatkinson Thanks for that information!

> This is the TTN payload:

Looks like a bunch of extra padding in there. So I've re-written the read data function which should help.

> The TTN duty cycle is actually 0.3% as a device can only send 30 seconds worth of data within a 24 hour period. Is this something you could change in your program?

I've changed it to `99.7` now, so hopefully that limits it to 0.3% duty cycle.

So try:
* `git pull`
* `python3 water_quality.py`

The output should now be something like: `DO:38.28,pH:10.468,RTD:-1023.000`

So on the TTN side we can parse the array of data by `,`, and then split the string by `:` to get the sensor and the value.

**Comment by mauriceatkinson** [comment]
@sighmon This is a fantastic step forward!!
I can now see the pi reporting:
Sending data from devices: DO:38.29,pH:0.000,RTD:-1023.000

and my Home Assistant is seeing the following via TTN MQTT
        "frm_payload": "RE86MzguMjkscEg6MC4wMDAsUlREOi0xMDIzLjAwMA==",
        "decoded_payload": {
            "receivedString": "DO:38.29,pH:0.000,RTD:-1023.000"

I am away for a couple of days from tomorrow but I will leave it running and see if it throws up anything unusual.

**Comment by mauriceatkinson** [comment]
@sighmon I have seen in the pi and TTN console logs that we are reading the sensors every 34 seconds.  This is too frequent and I wondered whether you could add some configurable delay into reading the sensors/sending the data.  I think reading/sending the data every 15 minutes is good enough

In addition I see there are many times when the sensors get read but there is nothing received by TTN although the pi log states it has been sent.  The high level view was that for every 5 sensor reads only 3 get sent to ttn.

**Comment by sighmon** [comment]
@mauriceatkinson Let's not trust their duty cycle calculations and do it ourselves. I've added `--sleep` as a command line argument, so you can now modify the time between uploads yourself. The default is `900 seconds` which is 15 minutes.

So do another `git pull` and now you can run it again with:

* `python3 water_quality.py`  (defaults to 900 seconds between transmissions)
* `python3 water_quality.py --sleep 300`  (for 5 minutes between transmissions)

**Comment by mauriceatkinson** [comment]
@sighmon the sleep function seems to work like a dream.

However in looking through the rasp pi logs I am seeing a couple of issues.  This error is easier to explain as there is an error in the logs and this repeats itself.  Is this to do with your code or the lora library we have pulled in?

2022-04-13 07:15:01,225 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:15:01,225 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:15:01,226 - registered - 572 - INFO - Already registered
2022-04-13 07:15:01,226 - getSendSettings - 259 - DEBUG - using send settings: freq 867.9 sf 9 bw 7
2022-04-13 07:15:01,226 - configureRadio - 173 - INFO -  freq=867.9 sf=9 bw=7
2022-04-13 07:15:01,229 - getFOpts - 560 - INFO - check for FOpts to attach to uplink len=0 FOpts=bytearray(b'')
2022-04-13 07:15:01,230 - getFOpts - 565 - INFO - no FOpts
2022-04-13 07:15:01,230 - saveCache - 489 - INFO - Saving MAC settings
2022-04-13 07:15:01,237 - _sendPacket - 644 - DEBUG - Sending packet raw payload = [64, 184, 58, 11, 38, 0, 191, 7, 1, 14, 248, 251, 131, 225, 101, 102, 200, 119, 19, 229, 196, 194, 233, 173, 57, 24, 100, 209, 220, 122, 177, 168, 158, 94, 128, 198, 244, 193, 26, 167, 63, 54, 125, 172, 137]
2022-04-13 07:15:01,549 - on_tx_done - 426 - INFO - switching to RX1
2022-04-13 07:15:01,550 - getRX1Settings - 278 - DEBUG - RX1 settings : freq 867.9 sf 9 bw 7
2022-04-13 07:15:01,550 - configureRadio - 173 - INFO -  freq=867.9 sf=9 bw=7
2022-04-13 07:15:01,553 - on_tx_done - 432 - INFO - setting timer delay {delay} to switch to RX2
2022-04-13 07:30:06,175 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:30:06,175 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:30:06,176 - registered - 572 - INFO - Already registered
2022-04-13 07:30:06,176 - _sendPacket - 664 - ERROR - list index out of range
Traceback (most recent call last):
  File "/home/pi/water-quality-lorawan-dragino-pi/dragino/dragino.py", line 601, in _sendPacket
    self.configureRadio(radioSettings.SEND)
  File "/home/pi/water-quality-lorawan-dragino-pi/dragino/dragino.py", line 167, in configureRadio
    freq,sf,bw=self.MAC.getSendSettings()
  File "/home/pi/water-quality-lorawan-dragino-pi/dragino/MAChandler.py", line 254, in getSendSettings
    freq=self.cache[CHANNEL_TX_FREQS][self.currentChannel]
IndexError: list index out of range
2022-04-13 07:45:10,805 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:45:10,806 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:45:10,806 - registered - 572 - INFO - Already registered
2022-04-13 07:45:10,806 - getSendSettings - 259 - DEBUG - using send settings: freq 867.3 sf 9 bw 7
2022-04-13 07:45:10,807 - configureRadio - 173 - INFO -  freq=867.3 sf=9 bw=7
2022-04-13 07:45:10,810 - getFOpts - 560 - INFO - check for FOpts to attach to uplink len=0 FOpts=bytearray(b'')
2022-04-13 07:45:10,810 - getFOpts - 565 - INFO - no FOpts
2022-04-13 07:45:10,811 - saveCache - 489 - INFO - Saving MAC settings
2022-04-13 07:45:10,818 - _sendPacket - 644 - DEBUG - Sending packet raw payload = [64, 184, 58, 11, 38, 0, 192, 7, 1, 69, 38, 121, 70, 183, 134, 70, 218, 89, 24, 112, 138, 157, 254, 67, 18, 49, 180, 165, 190, 181, 131, 171, 181, 38, 9, 173, 213, 19, 241, 221, 77, 6, 20, 150, 25]
2022-04-13 07:45:11,131 - on_tx_done - 426 - INFO - switching to RX1
2022-04-13 07:45:11,131 - getRX1Settings - 278 - DEBUG - RX1 settings : freq 867.3 sf 9 bw 7
2022-04-13 07:45:11,131 - configureRadio - 173 - INFO -  freq=867.3 sf=9 bw=7
2022-04-13 07:45:11,135 - on_tx_done - 432 - INFO - setting timer delay {delay} to switch to RX2
