### ISSUE TITLE
Submodule the dependencies

### ISSUE THREAD

**Issue by sighmon** [sighmon/water-quality-lorawan-dragino-pi#2]
- [x] Submodule `dragino`
- [x] Submodule `AtlasI2C`

**Comment by sighmon** [comment]
@mauriceatkinson Would you mind testing this code out where I'm including the dependent code in this repo too please? It'll help make it easier for others to get going and also help make it more resilient to changes in the code from Dragino and Atlas.

To test it:

* Clone this repo into a new folder: `git clone https://github.com/sighmon/water-quality-lorawan-dragino-pi.git water-quality-test-1`
* cd `water-quality-test-1`
* Run `git checkout add/2-submodule-dependencies` (to move to this branch)
* Run `git submodule update --init` (to add the `atlas` and `dragino` files)
* Copy your `dragino.ini` file from your current working directory
* Run `python3 water_quality.py`

Let me know if it runs as expected.

**Comment by mauriceatkinson** [comment]
@sighmon all done and it looks to be running as expected.  The only change is that I copy dragino.toml rather than dragino.ini

**Comment by sighmon** [comment]
@mauriceatkinson Brilliant thanks - I've merged that now.
